# Site settings
author: Toxsin Code
title: Just a simple blog
header-img: img/home-bg.png
email: jevoughnwisdom@gmail.com
copyright_name: Toxsin Code
description: > # this means to ignore newlines until "baseurl:"
  Insert flavor text here
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ToxsinCode

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
